/* This file, generated by REXDR Compiler for C++ version 1.7.1.2155. Build: Sep 17 2012. 10:31:38. */

#include "REXDR_CS_MessagesServiceDispatcher.h"


/*
 * message senders (module "REXDR_CS_Messages")
 */



/*
 * resource handlers. call message handlers. (module "REXDR_CS_Messages")
 */

/* resource handler for GetUserStatus */
static void __stdcall __ResourceHandlerForGetUserStatus( REXDR::Listener::Link::Handle link, const REXDR::MessageInfo& info, const REXDR::Request& req, void* context )
{
	GetUserStatus request;

	if ( false == request.Load( req ) ) {
		REXDR::Response resp;
		resp.status.code = REXDR::STATUS_BAD_REQUEST;
		resp.status.message = "Bad request. "; resp.status.message += request.GetLastError();

		REXDR::Listener::Link::Send( link, info, resp );
		return;
	}

	OnGetUserStatusHandler( link, info, request, context );
}


/* set resource handlers to dispatcher (module "REXDR_CS_Messages") */
void SetREXDR_CS_MessagesResourceHandler( REXDR::Dispatcher::Handle dispatcher, void* context )
{
	REXDR::Dispatcher::SetResourceHandler( dispatcher, "/stallon/request1/${userId}", REXDR::CMD_GET, __ResourceHandlerForGetUserStatus, context );
}


