/* This file, generated by REXDR Compiler for C++ version 1.7.1.2155. Build: Sep 17 2012. 10:31:38. */

#ifndef __REXDR_CS_MESSAGES_SERVICE_DISPATHCER_H_E839EAC5_45D8_11E2_B436_005056C00008__
#define __REXDR_CS_MESSAGES_SERVICE_DISPATCHER_H_E839EAC5_45D8_11E2_B436_005056C00008__

#include <REXDR/REXDRListenerAPI.h>
#include <REXDR/REXDRDispatcherAPI.h>
#include "REXDR_CS_Messages.h"


/*
 * set resource handlers to dispatcher (module "REXDR_CS_Messages")
 */
void SetREXDR_CS_MessagesResourceHandler( REXDR::Dispatcher::Handle dispatcher, void* context );


/*
 * callback functions for request messages (module "REXDR_CS_Messages")
 */
void OnGetUserStatusHandler( REXDR::Listener::Link::Handle link, const REXDR::MessageInfo& info, const GetUserStatus& request, void* context );


/*
 * send functions for response messages (module "REXDR_CS_Messages")
 */


#endif /* __REXDR_CS_MESSAGES_SERVICE_DISPATCHER_H_E839EAC5_45D8_11E2_B436_005056C00008__ */

